Fresh 6.0 install (Italiano)
99c10d52898783d3099a49cc82c908c98d6c1426

diff --git a/bin/git/mingw64/libexec/git-core/git-subtree b/bin/git/mingw64/libexec/git-core/git-subtree
--- a/bin/git/mingw64/libexec/git-core/git-subtree
+++ b/bin/git/mingw64/libexec/git-core/git-subtree
@@ -33,30 +33,22 @@ git subtree split --prefix=<prefix> [<commit>]
 git subtree pull  --prefix=<prefix> <repository> <ref>
 git subtree push  --prefix=<prefix> <repository> <refspec>
 --
-h,help!       show the help
-q,quiet!      quiet
-d,debug!      show debug messages
+h,help        show the help
+q             quiet
+d             show debug messages
 P,prefix=     the name of the subdir to split out
  options for 'split' (also: 'push')
 annotate=     add a prefix to commit message of new commits
-b,branch!=    create a new branch from the split subtree
+b,branch=     create a new branch from the split subtree
 ignore-joins  ignore prior --rejoin commits
 onto=         try connecting new tree to an existing one
 rejoin        merge the new branch back into HEAD
  options for 'add' and 'merge' (also: 'pull', 'split --rejoin', and 'push --rejoin')
 squash        merge subtree changes as a single commit
-m,message!=   use the given message as the commit message for the merge commit
+m,message=    use the given message as the commit message for the merge commit
 "
 
 indent=0
-
-# Usage: say [MSG...]
-say () {
-	if test -z "$arg_quiet"
-	then
-		printf '%s\n' "$*"
-	fi
-}
 
 # Usage: debug [MSG...]
 debug () {
@@ -68,7 +60,7 @@ debug () {
 
 # Usage: progress [MSG...]
 progress () {
-	if test -z "$arg_quiet"
+	if test -z "$GIT_QUIET"
 	then
 		if test -z "$arg_debug"
 		then
@@ -98,16 +90,8 @@ progress () {
 assert () {
 	if ! "$@"
 	then
-		die "fatal: assertion failed: $*"
+		die "assertion failed: $*"
 	fi
-}
-
-# Usage: die_incompatible_opt OPTION COMMAND
-die_incompatible_opt () {
-	assert test "$#" = 2
-	opt="$1"
-	arg_command="$2"
-	die "fatal: the '$opt' flag does not make sense with 'git subtree $arg_command'."
 }
 
 main () {
@@ -155,14 +139,13 @@ main () {
 		allow_addmerge=$arg_split_rejoin
 		;;
 	*)
-		die "fatal: unknown command '$arg_command'"
+		die "Unknown command '$arg_command'"
 		;;
 	esac
 	# Reset the arguments array for "real" flag parsing.
 	eval "$set_args"
 
 	# Begin "real" flag parsing.
-	arg_quiet=
 	arg_debug=
 	arg_prefix=
 	arg_split_branch=
@@ -178,22 +161,22 @@ main () {
 
 		case "$opt" in
 		-q)
-			arg_quiet=1
+			GIT_QUIET=1
 			;;
 		-d)
 			arg_debug=1
 			;;
 		--annotate)
-			test -n "$allow_split" || die_incompatible_opt "$opt" "$arg_command"
+			test -n "$allow_split" || die "The '$opt' flag does not make sense with 'git subtree $arg_command'."
 			arg_split_annotate="$1"
 			shift
 			;;
 		--no-annotate)
-			test -n "$allow_split" || die_incompatible_opt "$opt" "$arg_command"
+			test -n "$allow_split" || die "The '$opt' flag does not make sense with 'git subtree $arg_command'."
 			arg_split_annotate=
 			;;
 		-b)
-			test -n "$allow_split" || die_incompatible_opt "$opt" "$arg_command"
+			test -n "$allow_split" || die "The '$opt' flag does not make sense with 'git subtree $arg_command'."
 			arg_split_branch="$1"
 			shift
 			;;
@@ -202,7 +185,7 @@ main () {
 			shift
 			;;
 		-m)
-			test -n "$allow_addmerge" || die_incompatible_opt "$opt" "$arg_command"
+			test -n "$allow_addmerge" || die "The '$opt' flag does not make sense with 'git subtree $arg_command'."
 			arg_addmerge_message="$1"
 			shift
 			;;
@@ -210,41 +193,41 @@ main () {
 			arg_prefix=
 			;;
 		--onto)
-			test -n "$allow_split" || die_incompatible_opt "$opt" "$arg_command"
+			test -n "$allow_split" || die "The '$opt' flag does not make sense with 'git subtree $arg_command'."
 			arg_split_onto="$1"
 			shift
 			;;
 		--no-onto)
-			test -n "$allow_split" || die_incompatible_opt "$opt" "$arg_command"
+			test -n "$allow_split" || die "The '$opt' flag does not make sense with 'git subtree $arg_command'."
 			arg_split_onto=
 			;;
 		--rejoin)
-			test -n "$allow_split" || die_incompatible_opt "$opt" "$arg_command"
+			test -n "$allow_split" || die "The '$opt' flag does not make sense with 'git subtree $arg_command'."
 			;;
 		--no-rejoin)
-			test -n "$allow_split" || die_incompatible_opt "$opt" "$arg_command"
+			test -n "$allow_split" || die "The '$opt' flag does not make sense with 'git subtree $arg_command'."
 			;;
 		--ignore-joins)
-			test -n "$allow_split" || die_incompatible_opt "$opt" "$arg_command"
+			test -n "$allow_split" || die "The '$opt' flag does not make sense with 'git subtree $arg_command'."
 			arg_split_ignore_joins=1
 			;;
 		--no-ignore-joins)
-			test -n "$allow_split" || die_incompatible_opt "$opt" "$arg_command"
+			test -n "$allow_split" || die "The '$opt' flag does not make sense with 'git subtree $arg_command'."
 			arg_split_ignore_joins=
 			;;
 		--squash)
-			test -n "$allow_addmerge" || die_incompatible_opt "$opt" "$arg_command"
+			test -n "$allow_addmerge" || die "The '$opt' flag does not make sense with 'git subtree $arg_command'."
 			arg_addmerge_squash=1
 			;;
 		--no-squash)
-			test -n "$allow_addmerge" || die_incompatible_opt "$opt" "$arg_command"
+			test -n "$allow_addmerge" || die "The '$opt' flag does not make sense with 'git subtree $arg_command'."
 			arg_addmerge_squash=
 			;;
 		--)
 			break
 			;;
 		*)
-			die "fatal: unexpected option: $opt"
+			die "Unexpected option: $opt"
 			;;
 		esac
 	done
@@ -252,24 +235,24 @@ main () {
 
 	if test -z "$arg_prefix"
 	then
-		die "fatal: you must provide the --prefix option."
+		die "You must provide the --prefix option."
 	fi
 
 	case "$arg_command" in
 	add)
 		test -e "$arg_prefix" &&
-			die "fatal: prefix '$arg_prefix' already exists."
+			die "prefix '$arg_prefix' already exists."
 		;;
 	*)
 		test -e "$arg_prefix" ||
-			die "fatal: '$arg_prefix' does not exist; use 'git subtree add'"
+			die "'$arg_prefix' does not exist; use 'git subtree add'"
 		;;
 	esac
 
 	dir="$(dirname "$arg_prefix/.")"
 
 	debug "command: {$arg_command}"
-	debug "quiet: {$arg_quiet}"
+	debug "quiet: {$GIT_QUIET}"
 	debug "dir: {$dir}"
 	debug "opts: {$*}"
 	debug
@@ -282,11 +265,11 @@ cache_setup () {
 	assert test $# = 0
 	cachedir="$GIT_DIR/subtree-cache/$$"
 	rm -rf "$cachedir" ||
-		die "fatal: can't delete old cachedir: $cachedir"
+		die "Can't delete old cachedir: $cachedir"
 	mkdir -p "$cachedir" ||
-		die "fatal: can't create new cachedir: $cachedir"
+		die "Can't create new cachedir: $cachedir"
 	mkdir -p "$cachedir/notree" ||
-		die "fatal: can't create new cachedir: $cachedir/notree"
+		die "Can't create new cachedir: $cachedir/notree"
 	debug "Using cachedir: $cachedir" >&2
 }
 
@@ -342,7 +325,7 @@ cache_set () {
 		test "$oldrev" != "latest_new" &&
 		test -e "$cachedir/$oldrev"
 	then
-		die "fatal: cache for $oldrev already exists!"
+		die "cache for $oldrev already exists!"
 	fi
 	echo "$newrev" >"$cachedir/$oldrev"
 }
@@ -371,49 +354,13 @@ try_remove_previous () {
 	fi
 }
 
-# Usage: process_subtree_split_trailer SPLIT_HASH MAIN_HASH [REPOSITORY]
-process_subtree_split_trailer () {
-	assert test $# -ge 2
-	assert test $# -le 3
-	b="$1"
-	sq="$2"
-	repository=""
-	if test "$#" = 3
-	then
-		repository="$3"
-	fi
-	fail_msg="fatal: could not rev-parse split hash $b from commit $sq"
-	if ! sub="$(git rev-parse --verify --quiet "$b^{commit}")"
-	then
-		# if 'repository' was given, try to fetch the 'git-subtree-split' hash
-		# before 'rev-parse'-ing it again, as it might be a tag that we do not have locally
-		if test -n "${repository}"
-		then
-			git fetch "$repository" "$b"
-			sub="$(git rev-parse --verify --quiet "$b^{commit}")" ||
-				die "$fail_msg"
-		else
-			hint1=$(printf "hint: hash might be a tag, try fetching it from the subtree repository:")
-			hint2=$(printf "hint:    git fetch <subtree-repository> $b")
-			fail_msg=$(printf "$fail_msg\n$hint1\n$hint2")
-			die "$fail_msg"
-		fi
-	fi
-}
-
-# Usage: find_latest_squash DIR [REPOSITORY]
+# Usage: find_latest_squash DIR
 find_latest_squash () {
-	assert test $# -ge 1
-	assert test $# -le 2
-	dir="$1"
-	repository=""
-	if test "$#" = 2
-	then
-		repository="$2"
-	fi
-	debug "Looking for latest squash (dir=$dir, repository=$repository)..."
+	assert test $# = 1
+	debug "Looking for latest squash ($dir)..."
 	local indent=$(($indent + 1))
 
+	dir="$1"
 	sq=
 	main=
 	sub=
@@ -431,7 +378,8 @@ find_latest_squash () {
 			main="$b"
 			;;
 		git-subtree-split:)
-			process_subtree_split_trailer "$b" "$sq" "$repository"
+			sub="$(git rev-parse "$b^{commit}")" ||
+			die "could not rev-parse split hash $b from commit $sq"
 			;;
 		END)
 			if test -n "$sub"
@@ -455,20 +403,14 @@ find_latest_squash () {
 	done || exit $?
 }
 
-# Usage: find_existing_splits DIR REV [REPOSITORY]
+# Usage: find_existing_splits DIR REV
 find_existing_splits () {
-	assert test $# -ge 2
-	assert test $# -le 3
+	assert test $# = 2
 	debug "Looking for prior splits..."
 	local indent=$(($indent + 1))
 
 	dir="$1"
 	rev="$2"
-	repository=""
-	if test "$#" = 3
-	then
-		repository="$3"
-	fi
 	main=
 	sub=
 	local grep_format="^git-subtree-dir: $dir/*\$"
@@ -488,17 +430,18 @@ find_existing_splits () {
 			main="$b"
 			;;
 		git-subtree-split:)
-			process_subtree_split_trailer "$b" "$sq" "$repository"
+			sub="$(git rev-parse "$b^{commit}")" ||
+			die "could not rev-parse split hash $b from commit $sq"
 			;;
 		END)
 			debug "Main is: '$main'"
-			if test -z "$main" && test -n "$sub"
+			if test -z "$main" -a -n "$sub"
 			then
 				# squash commits refer to a subtree
 				debug "  Squash: $sq from $sub"
 				cache_set "$sq" "$sub"
 			fi
-			if test -n "$main" && test -n "$sub"
+			if test -n "$main" -a -n "$sub"
 			then
 				debug "  Prior: $main -> $sub"
 				cache_set $main $sub
@@ -538,7 +481,7 @@ copy_commit () {
 			cat
 		) |
 		git commit-tree "$2" $3  # reads the rest of stdin
-	) || die "fatal: can't copy commit $1"
+	) || die "Can't copy commit $1"
 }
 
 # Usage: add_msg DIR LATEST_OLD LATEST_NEW
@@ -641,16 +584,10 @@ subtree_for_commit () {
 	while read mode type tree name
 	do
 		assert test "$name" = "$dir"
-
-		case "$type" in
-		commit)
-			continue;; # ignore submodules
-		tree)
-			echo $tree
-			break;;
-		*)
-			die "fatal: tree entry is of type ${type}, expected tree or commit";;
-		esac
+		assert test "$type" = "tree" -o "$type" = "commit"
+		test "$type" = "commit" && continue  # ignore submodules
+		echo $tree
+		break
 	done || exit $?
 }
 
@@ -772,11 +709,11 @@ ensure_clean () {
 	assert test $# = 0
 	if ! git diff-index HEAD --exit-code --quiet 2>&1
 	then
-		die "fatal: working tree has modifications.  Cannot add."
+		die "Working tree has modifications.  Cannot add."
 	fi
 	if ! git diff-index --cached HEAD --exit-code --quiet 2>&1
 	then
-		die "fatal: index has modifications.  Cannot add."
+		die "Index has modifications.  Cannot add."
 	fi
 }
 
@@ -784,23 +721,7 @@ ensure_clean () {
 ensure_valid_ref_format () {
 	assert test $# = 1
 	git check-ref-format "refs/heads/$1" ||
-		die "fatal: '$1' does not look like a ref"
-}
-
-# Usage: check if a commit from another subtree should be
-# ignored from processing for splits
-should_ignore_subtree_split_commit () {
-	assert test $# = 1
-	local rev="$1"
-	if test -n "$(git log -1 --grep="git-subtree-dir:" $rev)"
-	then
-		if test -z "$(git log -1 --grep="git-subtree-mainline:" $rev)" &&
-			test -z "$(git log -1 --grep="git-subtree-dir: $arg_prefix$" $rev)"
-		then
-			return 0
-		fi
-	fi
-	return 1
+		die "'$1' does not look like a ref"
 }
 
 # Usage: process_split_commit REV PARENTS
@@ -866,7 +787,7 @@ cmd_add () {
 	if test $# -eq 1
 	then
 		git rev-parse -q --verify "$1^{commit}" >/dev/null ||
-			die "fatal: '$1' does not refer to a commit"
+			die "'$1' does not refer to a commit"
 
 		cmd_add_commit "$@"
 
@@ -881,7 +802,7 @@ cmd_add () {
 
 		cmd_add_repository "$@"
 	else
-		say >&2 "fatal: parameters were '$*'"
+		say >&2 "error: parameters were '$*'"
 		die "Provide either a commit or a repository and commit."
 	fi
 }
@@ -913,7 +834,7 @@ cmd_add_commit () {
 	git checkout -- "$dir" || exit $?
 	tree=$(git write-tree) || exit $?
 
-	headrev=$(git rev-parse --verify HEAD) || exit $?
+	headrev=$(git rev-parse HEAD) || exit $?
 	if test -n "$headrev" && test "$headrev" != "$rev"
 	then
 		headp="-p $headrev"
@@ -936,22 +857,17 @@ cmd_add_commit () {
 	say >&2 "Added dir '$dir'"
 }
 
-# Usage: cmd_split [REV] [REPOSITORY]
+# Usage: cmd_split [REV]
 cmd_split () {
 	if test $# -eq 0
 	then
 		rev=$(git rev-parse HEAD)
-	elif test $# -eq 1 || test $# -eq 2
+	elif test $# -eq 1
 	then
 		rev=$(git rev-parse -q --verify "$1^{commit}") ||
-			die "fatal: '$1' does not refer to a commit"
+			die "'$1' does not refer to a commit"
 	else
-		die "fatal: you must provide exactly one revision, and optionnally a repository.  Got: '$*'"
-	fi
-	repository=""
-	if test "$#" = 2
-	then
-		repository="$2"
+		die "You must provide exactly one revision.  Got: '$*'"
 	fi
 
 	if test -n "$arg_split_rejoin"
@@ -975,7 +891,7 @@ cmd_split () {
 		done || exit $?
 	fi
 
-	unrevs="$(find_existing_splits "$dir" "$rev" "$repository")" || exit $?
+	unrevs="$(find_existing_splits "$dir" "$rev")" || exit $?
 
 	# We can't restrict rev-list to only $dir here, because some of our
 	# parents have the $dir contents the root, and those won't match.
@@ -988,25 +904,13 @@ cmd_split () {
 	eval "$grl" |
 	while read rev parents
 	do
-		if should_ignore_subtree_split_commit "$rev"
-		then
-			continue
-		fi
-		parsedparents=''
-		for parent in $parents
-		do
-			if ! should_ignore_subtree_split_commit "$parent"
-			then
-				parsedparents="$parsedparents$parent "
-			fi
-		done
-		process_split_commit "$rev" "$parsedparents"
+		process_split_commit "$rev" "$parents"
 	done || exit $?
 
 	latest_new=$(cache_get latest_new) || exit $?
 	if test -z "$latest_new"
 	then
-		die "fatal: no new revisions were found"
+		die "No new revisions were found"
 	fi
 
 	if test -n "$arg_split_rejoin"
@@ -1027,7 +931,7 @@ cmd_split () {
 		then
 			if ! git merge-base --is-ancestor "$arg_split_branch" "$latest_new"
 			then
-				die "fatal: branch '$arg_split_branch' is not an ancestor of commit '$latest_new'."
+				die "Branch '$arg_split_branch' is not an ancestor of commit '$latest_new'."
 			fi
 			action='Updated'
 		else
@@ -1041,28 +945,20 @@ cmd_split () {
 	exit 0
 }
 
-# Usage: cmd_merge REV [REPOSITORY]
+# Usage: cmd_merge REV
 cmd_merge () {
-	if test $# -lt 1 || test $# -gt 2
-	then
-		die "fatal: you must provide exactly one revision, and optionally a repository. Got: '$*'"
-	fi
-
+	test $# -eq 1 ||
+		die "You must provide exactly one revision.  Got: '$*'"
 	rev=$(git rev-parse -q --verify "$1^{commit}") ||
-		die "fatal: '$1' does not refer to a commit"
-	repository=""
-	if test "$#" = 2
-	then
-		repository="$2"
-	fi
+		die "'$1' does not refer to a commit"
 	ensure_clean
 
 	if test -n "$arg_addmerge_squash"
 	then
-		first_split="$(find_latest_squash "$dir" "$repository")" || exit $?
+		first_split="$(find_latest_squash "$dir")" || exit $?
 		if test -z "$first_split"
 		then
-			die "fatal: can't squash-merge: '$dir' was never added."
+			die "Can't squash-merge: '$dir' was never added."
 		fi
 		set $first_split
 		old=$1
@@ -1090,21 +986,19 @@ cmd_merge () {
 cmd_pull () {
 	if test $# -ne 2
 	then
-		die "fatal: you must provide <repository> <ref>"
+		die "You must provide <repository> <ref>"
 	fi
-	repository="$1"
-	ref="$2"
 	ensure_clean
-	ensure_valid_ref_format "$ref"
-	git fetch "$repository" "$ref" || exit $?
-	cmd_merge FETCH_HEAD "$repository"
+	ensure_valid_ref_format "$2"
+	git fetch "$@" || exit $?
+	cmd_merge FETCH_HEAD
 }
 
 # Usage: cmd_push REPOSITORY [+][LOCALREV:]REMOTEREF
 cmd_push () {
 	if test $# -ne 2
 	then
-		die "fatal: you must provide <repository> <refspec>"
+		die "You must provide <repository> <refspec>"
 	fi
 	if test -e "$dir"
 	then
@@ -1119,13 +1013,13 @@ cmd_push () {
 		fi
 		ensure_valid_ref_format "$remoteref"
 		localrev_presplit=$(git rev-parse -q --verify "$localrevname_presplit^{commit}") ||
-			die "fatal: '$localrevname_presplit' does not refer to a commit"
+			die "'$localrevname_presplit' does not refer to a commit"
 
 		echo "git push using: " "$repository" "$refspec"
-		localrev=$(cmd_split "$localrev_presplit" "$repository") || die
+		localrev=$(cmd_split "$localrev_presplit") || die
 		git push "$repository" "$localrev":"refs/heads/$remoteref"
 	else
-		die "fatal: '$dir' must already exist. Try 'git subtree add'."
+		die "'$dir' must already exist. Try 'git subtree add'."
 	fi
 }
 
